export const amenities = [
  { key: 'WiFi', label: 'Wi-Fi', icon: 'wifi' },
  { key: 'Fireplace', label: 'Fireplace', icon: 'fireplace' },
  { key: 'Garden', label: 'Garden', icon: 'garden' },
  { key: 'Kitchen', label: 'Kitchen', icon: 'kitchen' },
  { key: 'Washer', label: 'Washer', icon: 'washer' },
  { key: 'TV', label: 'TV', icon: 'tv' },
  { key: 'Solar Power', label: 'Solar Power', icon: 'solar-power' },
  { key: 'Outdoor Shower', label: 'Outdoor Shower', icon: 'outdoor-shower' },
  { key: 'Kayaks', label: 'Kayaks', icon: 'kayak' },
  { key: 'Deck', label: 'Deck', icon: 'deck' },
  { key: 'Nature View', label: 'Nature View', icon: 'nature-view' },
  { key: 'Heated Floors', label: 'Heated Floors', icon: 'heated-floors' },
  { key: 'Balcony', label: 'Balcony', icon: 'balcony' },
  { key: 'AC', label: 'A/C', icon: 'ac' },
  { key: 'Kitchenette', label: 'Kitchenette', icon: 'kitchenette' },
  { key: 'Coffee Maker', label: 'Coffee Maker', icon: 'coffee-maker' },
  { key: 'Bike Rental', label: 'Bike Rental', icon: 'bike-rental' },
  { key: 'Mosquito Net', label: 'Mosquito Net', icon: 'mosquito-net' },
  { key: 'Elevator', label: 'Elevator', icon: 'elevator' },
  { key: 'Work Desk', label: 'Work Desk', icon: 'desk' },
  { key: 'Smart TV', label: 'Smart TV', icon: 'smart-tv' },
  { key: 'Backyard', label: 'Backyard', icon: 'backyard' },
  { key: 'Art Decor', label: 'Art Decor', icon: 'art' },
  { key: 'Workspace', label: 'Workspace', icon: 'workspace' },
  { key: 'Crib', label: 'Crib', icon: 'crib' },
  { key: 'Historic Charm', label: 'Historic Charm', icon: 'historic-charm' },
  { key: 'Terrace', label: 'Terrace', icon: 'terrace' },
  { key: 'Books', label: 'Books', icon: 'books' },
  { key: 'Historic Decor', label: 'Historic Decor', icon: 'historic-decor' },
  { key: 'Beach Access', label: 'Beach Access', icon: 'beach-access' },
  { key: 'Mountain View', label: 'Mountain View', icon: 'mountain-view' },
]
