export const amenities = [
  { key: 'AC', label: 'A/C', icon: 'ac' },
  { key: 'Balcony', label: 'Balcony', icon: 'balcony' },
  { key: 'Bikes', label: 'Bikes', icon: 'bikes' },
  { key: 'Ceiling Fan', label: 'Ceiling Fan', icon: 'ceiling-fan' },
  { key: 'Coffee', label: 'Coffee Maker', icon: 'coffee' },
  { key: 'Desk', label: 'Work Desk', icon: 'desk' },
  { key: 'Exercise Equipment', label: 'Exercise Equipment', icon: 'exercise-equipment' },
  { key: 'Fire Extinguisher', label: 'Fire Extinguisher', icon: 'fire-extinguisher' },
  { key: 'Fireplace', label: 'Fireplace', icon: 'fireplace' },
  { key: 'Free Parking', label: 'Free Parking', icon: 'free-parking' },
  { key: 'Garden', label: 'Garden', icon: 'garden' },
  { key: 'Hair Dryer', label: 'Hair Dryer', icon: 'hair-dryer' },
  { key: 'Hammock', label: 'Hammock', icon: 'hammock' },
  { key: 'Hot Water', label: 'Hot Water', icon: 'hot-water' },
  { key: 'Iron', label: 'Iron', icon: 'iron' },
  { key: 'Kitchen', label: 'Kitchen', icon: 'kitchen' },
  { key: 'Mountain View', label: 'Mountain View', icon: 'mountain-view' },
  { key: 'Nature View', label: 'Nature View', icon: 'nature-view' },
  { key: 'Pets Allowed', label: 'Pets Allowed', icon: 'pets-allowed' },
  { key: 'Refrigerator', label: 'Refrigerator', icon: 'refrigerator' },
  { key: 'Safe', label: 'Safe', icon: 'safe' },
  { key: 'Self Check-In', label: 'Self Check-In', icon: 'self-check-in' },
  { key: 'Shampoo', label: 'Shampoo', icon: 'shampoo' },
  { key: 'Smoke Alarm', label: 'Smoke Alarm', icon: 'smoke-alarm' },
  { key: 'Toaster', label: 'Toaster', icon: 'toaster' },
  { key: 'TV', label: 'TV', icon: 'tv' },
  { key: 'Washer', label: 'Washer', icon: 'washer' },
  { key: 'WiFi', label: 'Wi-Fi', icon: 'wifi' },
  { key: 'Wine Glasses', label: 'Wine Glasses', icon: 'wine-glasses' },
]
